// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package com.pika.app.rust.share

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_pika_share_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_pika_share_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "pika_share"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "pika_share"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_pika_share_checksum_func_share_ack(
    ): Short
    external fun uniffi_pika_share_checksum_func_share_dequeue_batch(
    ): Short
    external fun uniffi_pika_share_checksum_func_share_enqueue(
    ): Short
    external fun uniffi_pika_share_checksum_func_share_gc(
    ): Short
    external fun uniffi_pika_share_checksum_func_share_list_recent_results(
    ): Short
    external fun ffi_pika_share_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "pika_share"))
        
    }
    external fun uniffi_pika_share_fn_func_share_ack(`rootDir`: RustBuffer.ByValue,`ack`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_pika_share_fn_func_share_dequeue_batch(`rootDir`: RustBuffer.ByValue,`nowMsOverride`: Long,`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_pika_share_fn_func_share_enqueue(`rootDir`: RustBuffer.ByValue,`request`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_pika_share_fn_func_share_gc(`rootDir`: RustBuffer.ByValue,`nowMsOverride`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_pika_share_fn_func_share_list_recent_results(`rootDir`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_pika_share_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_pika_share_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_pika_share_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_pika_share_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_pika_share_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_pika_share_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_pika_share_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_pika_share_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_pika_share_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_pika_share_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_pika_share_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_pika_share_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_pika_share_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_pika_share_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_pika_share_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_pika_share_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_pika_share_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_pika_share_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_pika_share_checksum_func_share_ack() != 11529.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pika_share_checksum_func_share_dequeue_batch() != 35892.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pika_share_checksum_func_share_enqueue() != 55817.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pika_share_checksum_func_share_gc() != 61553.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_pika_share_checksum_func_share_list_recent_results() != 8846.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class ShareDispatchAck (
    var `itemId`: kotlin.String
    , 
    var `status`: ShareAckStatus
    , 
    var `errorCode`: kotlin.String?
    , 
    var `errorMessage`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareDispatchAck: FfiConverterRustBuffer<ShareDispatchAck> {
    override fun read(buf: ByteBuffer): ShareDispatchAck {
        return ShareDispatchAck(
            FfiConverterString.read(buf),
            FfiConverterTypeShareAckStatus.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: ShareDispatchAck) = (
            FfiConverterString.allocationSize(value.`itemId`) +
            FfiConverterTypeShareAckStatus.allocationSize(value.`status`) +
            FfiConverterOptionalString.allocationSize(value.`errorCode`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: ShareDispatchAck, buf: ByteBuffer) {
            FfiConverterString.write(value.`itemId`, buf)
            FfiConverterTypeShareAckStatus.write(value.`status`, buf)
            FfiConverterOptionalString.write(value.`errorCode`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class ShareDispatchJob (
    var `itemId`: kotlin.String
    , 
    var `chatId`: kotlin.String
    , 
    var `kind`: ShareDispatchKind
    , 
    var `attemptCount`: kotlin.UInt
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareDispatchJob: FfiConverterRustBuffer<ShareDispatchJob> {
    override fun read(buf: ByteBuffer): ShareDispatchJob {
        return ShareDispatchJob(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeShareDispatchKind.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ShareDispatchJob) = (
            FfiConverterString.allocationSize(value.`itemId`) +
            FfiConverterString.allocationSize(value.`chatId`) +
            FfiConverterTypeShareDispatchKind.allocationSize(value.`kind`) +
            FfiConverterUInt.allocationSize(value.`attemptCount`)
    )

    override fun write(value: ShareDispatchJob, buf: ByteBuffer) {
            FfiConverterString.write(value.`itemId`, buf)
            FfiConverterString.write(value.`chatId`, buf)
            FfiConverterTypeShareDispatchKind.write(value.`kind`, buf)
            FfiConverterUInt.write(value.`attemptCount`, buf)
    }
}



data class ShareEnqueueRequest (
    var `chatId`: kotlin.String
    , 
    var `composeText`: kotlin.String
    , 
    var `payloadKind`: SharePayloadKind
    , 
    var `payloadText`: kotlin.String?
    , 
    var `mediaRelativePath`: kotlin.String?
    , 
    var `mediaMimeType`: kotlin.String?
    , 
    var `mediaFilename`: kotlin.String?
    , 
    var `mediaBatch`: List<ShareMediaBatchEntry>?
    , 
    var `clientRequestId`: kotlin.String
    , 
    var `createdAtMs`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareEnqueueRequest: FfiConverterRustBuffer<ShareEnqueueRequest> {
    override fun read(buf: ByteBuffer): ShareEnqueueRequest {
        return ShareEnqueueRequest(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeSharePayloadKind.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalSequenceTypeShareMediaBatchEntry.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: ShareEnqueueRequest) = (
            FfiConverterString.allocationSize(value.`chatId`) +
            FfiConverterString.allocationSize(value.`composeText`) +
            FfiConverterTypeSharePayloadKind.allocationSize(value.`payloadKind`) +
            FfiConverterOptionalString.allocationSize(value.`payloadText`) +
            FfiConverterOptionalString.allocationSize(value.`mediaRelativePath`) +
            FfiConverterOptionalString.allocationSize(value.`mediaMimeType`) +
            FfiConverterOptionalString.allocationSize(value.`mediaFilename`) +
            FfiConverterOptionalSequenceTypeShareMediaBatchEntry.allocationSize(value.`mediaBatch`) +
            FfiConverterString.allocationSize(value.`clientRequestId`) +
            FfiConverterULong.allocationSize(value.`createdAtMs`)
    )

    override fun write(value: ShareEnqueueRequest, buf: ByteBuffer) {
            FfiConverterString.write(value.`chatId`, buf)
            FfiConverterString.write(value.`composeText`, buf)
            FfiConverterTypeSharePayloadKind.write(value.`payloadKind`, buf)
            FfiConverterOptionalString.write(value.`payloadText`, buf)
            FfiConverterOptionalString.write(value.`mediaRelativePath`, buf)
            FfiConverterOptionalString.write(value.`mediaMimeType`, buf)
            FfiConverterOptionalString.write(value.`mediaFilename`, buf)
            FfiConverterOptionalSequenceTypeShareMediaBatchEntry.write(value.`mediaBatch`, buf)
            FfiConverterString.write(value.`clientRequestId`, buf)
            FfiConverterULong.write(value.`createdAtMs`, buf)
    }
}



data class ShareGcStats (
    var `requeuedInflight`: kotlin.UInt
    , 
    var `removedPending`: kotlin.UInt
    , 
    var `removedInflight`: kotlin.UInt
    , 
    var `removedResults`: kotlin.UInt
    , 
    var `removedIndexes`: kotlin.UInt
    , 
    var `removedOrphanMedia`: kotlin.UInt
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareGcStats: FfiConverterRustBuffer<ShareGcStats> {
    override fun read(buf: ByteBuffer): ShareGcStats {
        return ShareGcStats(
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ShareGcStats) = (
            FfiConverterUInt.allocationSize(value.`requeuedInflight`) +
            FfiConverterUInt.allocationSize(value.`removedPending`) +
            FfiConverterUInt.allocationSize(value.`removedInflight`) +
            FfiConverterUInt.allocationSize(value.`removedResults`) +
            FfiConverterUInt.allocationSize(value.`removedIndexes`) +
            FfiConverterUInt.allocationSize(value.`removedOrphanMedia`)
    )

    override fun write(value: ShareGcStats, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`requeuedInflight`, buf)
            FfiConverterUInt.write(value.`removedPending`, buf)
            FfiConverterUInt.write(value.`removedInflight`, buf)
            FfiConverterUInt.write(value.`removedResults`, buf)
            FfiConverterUInt.write(value.`removedIndexes`, buf)
            FfiConverterUInt.write(value.`removedOrphanMedia`, buf)
    }
}



data class ShareMediaBatchDispatchItem (
    var `mimeType`: kotlin.String
    , 
    var `filename`: kotlin.String
    , 
    var `dataBase64`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareMediaBatchDispatchItem: FfiConverterRustBuffer<ShareMediaBatchDispatchItem> {
    override fun read(buf: ByteBuffer): ShareMediaBatchDispatchItem {
        return ShareMediaBatchDispatchItem(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ShareMediaBatchDispatchItem) = (
            FfiConverterString.allocationSize(value.`mimeType`) +
            FfiConverterString.allocationSize(value.`filename`) +
            FfiConverterString.allocationSize(value.`dataBase64`)
    )

    override fun write(value: ShareMediaBatchDispatchItem, buf: ByteBuffer) {
            FfiConverterString.write(value.`mimeType`, buf)
            FfiConverterString.write(value.`filename`, buf)
            FfiConverterString.write(value.`dataBase64`, buf)
    }
}



data class ShareMediaBatchEntry (
    var `relativePath`: kotlin.String
    , 
    var `mimeType`: kotlin.String
    , 
    var `filename`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareMediaBatchEntry: FfiConverterRustBuffer<ShareMediaBatchEntry> {
    override fun read(buf: ByteBuffer): ShareMediaBatchEntry {
        return ShareMediaBatchEntry(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ShareMediaBatchEntry) = (
            FfiConverterString.allocationSize(value.`relativePath`) +
            FfiConverterString.allocationSize(value.`mimeType`) +
            FfiConverterString.allocationSize(value.`filename`)
    )

    override fun write(value: ShareMediaBatchEntry, buf: ByteBuffer) {
            FfiConverterString.write(value.`relativePath`, buf)
            FfiConverterString.write(value.`mimeType`, buf)
            FfiConverterString.write(value.`filename`, buf)
    }
}



data class ShareQueueReceipt (
    var `itemId`: kotlin.String
    , 
    var `queuedAtMs`: kotlin.ULong
    , 
    var `status`: ShareQueueStatus
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareQueueReceipt: FfiConverterRustBuffer<ShareQueueReceipt> {
    override fun read(buf: ByteBuffer): ShareQueueReceipt {
        return ShareQueueReceipt(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterTypeShareQueueStatus.read(buf),
        )
    }

    override fun allocationSize(value: ShareQueueReceipt) = (
            FfiConverterString.allocationSize(value.`itemId`) +
            FfiConverterULong.allocationSize(value.`queuedAtMs`) +
            FfiConverterTypeShareQueueStatus.allocationSize(value.`status`)
    )

    override fun write(value: ShareQueueReceipt, buf: ByteBuffer) {
            FfiConverterString.write(value.`itemId`, buf)
            FfiConverterULong.write(value.`queuedAtMs`, buf)
            FfiConverterTypeShareQueueStatus.write(value.`status`, buf)
    }
}



data class ShareResult (
    var `itemId`: kotlin.String
    , 
    var `clientRequestId`: kotlin.String
    , 
    var `chatId`: kotlin.String
    , 
    var `status`: ShareAckStatus
    , 
    var `updatedAtMs`: kotlin.ULong
    , 
    var `isTerminal`: kotlin.Boolean
    , 
    var `errorCode`: kotlin.String?
    , 
    var `errorMessage`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareResult: FfiConverterRustBuffer<ShareResult> {
    override fun read(buf: ByteBuffer): ShareResult {
        return ShareResult(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeShareAckStatus.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: ShareResult) = (
            FfiConverterString.allocationSize(value.`itemId`) +
            FfiConverterString.allocationSize(value.`clientRequestId`) +
            FfiConverterString.allocationSize(value.`chatId`) +
            FfiConverterTypeShareAckStatus.allocationSize(value.`status`) +
            FfiConverterULong.allocationSize(value.`updatedAtMs`) +
            FfiConverterBoolean.allocationSize(value.`isTerminal`) +
            FfiConverterOptionalString.allocationSize(value.`errorCode`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: ShareResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`itemId`, buf)
            FfiConverterString.write(value.`clientRequestId`, buf)
            FfiConverterString.write(value.`chatId`, buf)
            FfiConverterTypeShareAckStatus.write(value.`status`, buf)
            FfiConverterULong.write(value.`updatedAtMs`, buf)
            FfiConverterBoolean.write(value.`isTerminal`, buf)
            FfiConverterOptionalString.write(value.`errorCode`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}




enum class ShareAckStatus {
    
    ACCEPTED_BY_CORE,
    RETRYABLE_FAILURE,
    PERMANENT_FAILURE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeShareAckStatus: FfiConverterRustBuffer<ShareAckStatus> {
    override fun read(buf: ByteBuffer) = try {
        ShareAckStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ShareAckStatus) = 4UL

    override fun write(value: ShareAckStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





sealed class ShareDispatchKind {
    
    data class Message(
        val `content`: kotlin.String) : ShareDispatchKind()
        
    {
        

        companion object
    }
    
    data class Media(
        val `caption`: kotlin.String, 
        val `mimeType`: kotlin.String, 
        val `filename`: kotlin.String, 
        val `dataBase64`: kotlin.String) : ShareDispatchKind()
        
    {
        

        companion object
    }
    
    data class MediaBatch(
        val `caption`: kotlin.String, 
        val `items`: List<com.pika.app.rust.share.ShareMediaBatchDispatchItem>) : ShareDispatchKind()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeShareDispatchKind : FfiConverterRustBuffer<ShareDispatchKind>{
    override fun read(buf: ByteBuffer): ShareDispatchKind {
        return when(buf.getInt()) {
            1 -> ShareDispatchKind.Message(
                FfiConverterString.read(buf),
                )
            2 -> ShareDispatchKind.Media(
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            3 -> ShareDispatchKind.MediaBatch(
                FfiConverterString.read(buf),
                FfiConverterSequenceTypeShareMediaBatchDispatchItem.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ShareDispatchKind) = when(value) {
        is ShareDispatchKind.Message -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`content`)
            )
        }
        is ShareDispatchKind.Media -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`caption`)
                + FfiConverterString.allocationSize(value.`mimeType`)
                + FfiConverterString.allocationSize(value.`filename`)
                + FfiConverterString.allocationSize(value.`dataBase64`)
            )
        }
        is ShareDispatchKind.MediaBatch -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterString.allocationSize(value.`caption`)
                + FfiConverterSequenceTypeShareMediaBatchDispatchItem.allocationSize(value.`items`)
            )
        }
    }

    override fun write(value: ShareDispatchKind, buf: ByteBuffer) {
        when(value) {
            is ShareDispatchKind.Message -> {
                buf.putInt(1)
                FfiConverterString.write(value.`content`, buf)
                Unit
            }
            is ShareDispatchKind.Media -> {
                buf.putInt(2)
                FfiConverterString.write(value.`caption`, buf)
                FfiConverterString.write(value.`mimeType`, buf)
                FfiConverterString.write(value.`filename`, buf)
                FfiConverterString.write(value.`dataBase64`, buf)
                Unit
            }
            is ShareDispatchKind.MediaBatch -> {
                buf.putInt(3)
                FfiConverterString.write(value.`caption`, buf)
                FfiConverterSequenceTypeShareMediaBatchDispatchItem.write(value.`items`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}







sealed class ShareException: kotlin.Exception() {
    
    class InvalidRequest(
        
        val v1: kotlin.String
        ) : ShareException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class Io(
        
        val v1: kotlin.String
        ) : ShareException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class Serialization(
        
        val v1: kotlin.String
        ) : ShareException() {
        override val message
            get() = "v1=${ v1 }"
    }
    
    class NotFound(
        
        val v1: kotlin.String
        ) : ShareException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ShareException> {
        override fun lift(error_buf: RustBuffer.ByValue): ShareException = FfiConverterTypeShareError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeShareError : FfiConverterRustBuffer<ShareException> {
    override fun read(buf: ByteBuffer): ShareException {
        

        return when(buf.getInt()) {
            1 -> ShareException.InvalidRequest(
                FfiConverterString.read(buf),
                )
            2 -> ShareException.Io(
                FfiConverterString.read(buf),
                )
            3 -> ShareException.Serialization(
                FfiConverterString.read(buf),
                )
            4 -> ShareException.NotFound(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ShareException): ULong {
        return when(value) {
            is ShareException.InvalidRequest -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is ShareException.Io -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is ShareException.Serialization -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
            is ShareException.NotFound -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: ShareException, buf: ByteBuffer) {
        when(value) {
            is ShareException.InvalidRequest -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is ShareException.Io -> {
                buf.putInt(2)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is ShareException.Serialization -> {
                buf.putInt(3)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
            is ShareException.NotFound -> {
                buf.putInt(4)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class SharePayloadKind {
    
    TEXT,
    URL,
    IMAGE,
    IMAGE_BATCH;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeSharePayloadKind: FfiConverterRustBuffer<SharePayloadKind> {
    override fun read(buf: ByteBuffer) = try {
        SharePayloadKind.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: SharePayloadKind) = 4UL

    override fun write(value: SharePayloadKind, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class ShareQueueStatus {
    
    QUEUED,
    DUPLICATE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeShareQueueStatus: FfiConverterRustBuffer<ShareQueueStatus> {
    override fun read(buf: ByteBuffer) = try {
        ShareQueueStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ShareQueueStatus) = 4UL

    override fun write(value: ShareQueueStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalSequenceTypeShareMediaBatchEntry: FfiConverterRustBuffer<List<ShareMediaBatchEntry>?> {
    override fun read(buf: ByteBuffer): List<ShareMediaBatchEntry>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterSequenceTypeShareMediaBatchEntry.read(buf)
    }

    override fun allocationSize(value: List<ShareMediaBatchEntry>?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterSequenceTypeShareMediaBatchEntry.allocationSize(value)
        }
    }

    override fun write(value: List<ShareMediaBatchEntry>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterSequenceTypeShareMediaBatchEntry.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeShareDispatchJob: FfiConverterRustBuffer<List<ShareDispatchJob>> {
    override fun read(buf: ByteBuffer): List<ShareDispatchJob> {
        val len = buf.getInt()
        return List<ShareDispatchJob>(len) {
            FfiConverterTypeShareDispatchJob.read(buf)
        }
    }

    override fun allocationSize(value: List<ShareDispatchJob>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeShareDispatchJob.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ShareDispatchJob>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeShareDispatchJob.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeShareMediaBatchDispatchItem: FfiConverterRustBuffer<List<ShareMediaBatchDispatchItem>> {
    override fun read(buf: ByteBuffer): List<ShareMediaBatchDispatchItem> {
        val len = buf.getInt()
        return List<ShareMediaBatchDispatchItem>(len) {
            FfiConverterTypeShareMediaBatchDispatchItem.read(buf)
        }
    }

    override fun allocationSize(value: List<ShareMediaBatchDispatchItem>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeShareMediaBatchDispatchItem.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ShareMediaBatchDispatchItem>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeShareMediaBatchDispatchItem.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeShareMediaBatchEntry: FfiConverterRustBuffer<List<ShareMediaBatchEntry>> {
    override fun read(buf: ByteBuffer): List<ShareMediaBatchEntry> {
        val len = buf.getInt()
        return List<ShareMediaBatchEntry>(len) {
            FfiConverterTypeShareMediaBatchEntry.read(buf)
        }
    }

    override fun allocationSize(value: List<ShareMediaBatchEntry>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeShareMediaBatchEntry.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ShareMediaBatchEntry>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeShareMediaBatchEntry.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeShareResult: FfiConverterRustBuffer<List<ShareResult>> {
    override fun read(buf: ByteBuffer): List<ShareResult> {
        val len = buf.getInt()
        return List<ShareResult>(len) {
            FfiConverterTypeShareResult.read(buf)
        }
    }

    override fun allocationSize(value: List<ShareResult>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeShareResult.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ShareResult>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeShareResult.write(it, buf)
        }
    }
}
    @Throws(ShareException::class) fun `shareAck`(`rootDir`: kotlin.String, `ack`: ShareDispatchAck)
        = 
    uniffiRustCallWithError(ShareException) { _status ->
    UniffiLib.uniffi_pika_share_fn_func_share_ack(
    
        FfiConverterString.lower(`rootDir`),FfiConverterTypeShareDispatchAck.lower(`ack`),_status)
}
    
    

    @Throws(ShareException::class) fun `shareDequeueBatch`(`rootDir`: kotlin.String, `nowMsOverride`: kotlin.ULong, `limit`: kotlin.UInt): List<ShareDispatchJob> {
            return FfiConverterSequenceTypeShareDispatchJob.lift(
    uniffiRustCallWithError(ShareException) { _status ->
    UniffiLib.uniffi_pika_share_fn_func_share_dequeue_batch(
    
        FfiConverterString.lower(`rootDir`),FfiConverterULong.lower(`nowMsOverride`),FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    

    @Throws(ShareException::class) fun `shareEnqueue`(`rootDir`: kotlin.String, `request`: ShareEnqueueRequest): ShareQueueReceipt {
            return FfiConverterTypeShareQueueReceipt.lift(
    uniffiRustCallWithError(ShareException) { _status ->
    UniffiLib.uniffi_pika_share_fn_func_share_enqueue(
    
        FfiConverterString.lower(`rootDir`),FfiConverterTypeShareEnqueueRequest.lower(`request`),_status)
}
    )
    }
    

    @Throws(ShareException::class) fun `shareGc`(`rootDir`: kotlin.String, `nowMsOverride`: kotlin.ULong): ShareGcStats {
            return FfiConverterTypeShareGcStats.lift(
    uniffiRustCallWithError(ShareException) { _status ->
    UniffiLib.uniffi_pika_share_fn_func_share_gc(
    
        FfiConverterString.lower(`rootDir`),FfiConverterULong.lower(`nowMsOverride`),_status)
}
    )
    }
    

    @Throws(ShareException::class) fun `shareListRecentResults`(`rootDir`: kotlin.String, `limit`: kotlin.UInt): List<ShareResult> {
            return FfiConverterSequenceTypeShareResult.lift(
    uniffiRustCallWithError(ShareException) { _status ->
    UniffiLib.uniffi_pika_share_fn_func_share_list_recent_results(
    
        FfiConverterString.lower(`rootDir`),FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    


